notice/urls.py
from django.contrib import admin
from django.urls import path
from . import views
# from .views import *

# notice    >    urls.py
app_name='notice'
urlpatterns = [
    path('noticeList/', views.list, name="list"),
    # name은 중복 불가
    path('noticeList/<int:page>', views.list, name='listPage'),
    path('noticeWrite/', views.write, name="write"),
    path('noticeSelect/<int:num>', views.select, name="select"),
    path('noticeUpdate/<int:num>', views.update, name="update"),
    path('noticeDelete/<int:num>', views.delete, name="delete")
]

project1/urls.py
from django.contrib import admin
from django.urls import path, include

# project1  >   urls.py

urlpatterns = [
    path('admin/', admin.site.urls),
    path('notice/', include('notice.urls'))
]

notice/models.py
from django.db import models

# Create your models here.

# class 생성
class Notice(models.Model):
    # 클래스 변수
    num = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    writer = models.CharField(max_length=200)
    contents = models.TextField(null=True)
    createDate = models.DateTimeField(auto_now_add=True)
    hit = models.IntegerField(default="0")

notice/views.py
from django.shortcuts import render, redirect
# class를 불러올 때 편의 상
from .models import Notice
from django.core.paginator import Paginator
from .customPager import CustomPager

# Create your views here.
def delete(request, num) :
    notice = Notice(num=num)
    notice.delete()
    return redirect("notice:list")

def update(request, num) :
    if request.method=='POST':
        notice = Notice.objects.get(pk=num)
        notice.title=request.POST['title']
        notice.contents=request.POST['contents']
        notice.save()
        return redirect("notice:list")
    else :
        notice = Notice.objects.get(pk=num)
        context = {"vo":notice, "board":"NoticeUpdate"}
        return render(request, 'notice/write.html', context)

def select(request, num=1) :
    notice = Notice.objects.get(pk=num)
    context = {"vo":notice,"board":"NoticeSelect",}
    return render(request, 'notice/select.html',context)

def write(request) :
    if request.method=='POST':
        #                                       POST로 title이라는 변수를 받아온다
        notice =  Notice(title=request.POST['title'], writer=request.POST['writer'], contents=request.POST['contents'])
        notice.save()
        return redirect("/notice/noticeList")
    else :
        print("Write Form")
        return render(request, 'notice/write.html', {"board":"NoticeWrite"})


#                               default=1로 설정
def list(request, page=1, kind="title", search="") :
    # QuerySet
    # select * from notice_notice
    # notice = Notice.objects.all()
    # select * from notice_notice order by num desc
    # notice = Notice.objects.order_by("-num")

    # slicing ------------------------------------------------------------------
    # start = (page-1)*2
    # last = (page)*2
    # select * from notice_notice order by num desc index 0번 부터 2번 전까지 가져오기
    # notice = Notice.objects.order_by("-num")[start:last]

    # Paginator --------------------------------------------------------------
    # notice = Notice.objects.order_by("-num")
    # Paginator(QuerySet, 가져올 페이지 수)
    # notice = Paginator(notice, 2)
    # 실제 조회
    # notice = notice.get_page(page)

    # CustomPager ----------------------------------------------------------
    customPager = CustomPager(page, kind, search) 

    notice = Notice.objects.order_by("-num")
    notice = Paginator(notice, 2)
    
    customPager.makePage(notice.num_pages)

    notice = notice.get_page(customPager.page)

    context = {"board":"NoticeList", "list":notice,"pager":customPager,}
    return render(request, 'notice/list.html',context)

notice/templates/notice/list copy.html
{% extends 'base.html' %}

{% block contents %}
<div class="container">
    <h2>{{board}}</h2>
    <table class="table table-striped">   
        <tr>
            <td>Num</td>
            <td>Title</td>
            <td>Writer</td>
            <td>Date</td>
            <td>Hit</td>
        </tr>
        
        {% for board in list %}   
        <tr>
            <td>{{board.num}}</td>
            <td>{{board.title}}</td>
            <td>{{board.writer}}</td>
            <td>{{board.date}}</td>
            <td>{{board.hit}}</td>
        </tr>
        {% endfor %}

    </table>

    <ul class="pagination">
        {% if list.has_previous %}
        <li><a href="../{{list.previous_page_number}}">이전</a></li>
        {% endif %}

        {% if list.has_next %}
        <li><a href="../{{list.next_page_number}}">다음</a></li>
        {% endif %}
      </ul>


</div>
{% endblock contents %}

notice/templates/notice/list.html
{% extends 'base.html' %}

{% block contents %}
<div class="container">
    <h2>{{board}}</h2>
    <table class="table table-striped">   
        <tr>
            <td>Num</td>
            <td>Title</td>
            <td>Writer</td>
            <td>Date</td>
            <td>Hit</td>
        </tr>
        
        {% for board in list %}   
        <tr>
            <td>{{board.num}}</td>
            <td><a href="{% url 'notice:select' board.num %}">{{board.title}}</a></td>
            <td>{{board.writer}}</td>
            <td>{{board.date}}</td>
            <td>{{board.hit}}</td>
        </tr>
        {% endfor %}

    </table>

    <ul class="pagination">
        {% if pager.pre %}
        <li><a href="{% url 'notice:listPage' page=pager.startNum %}">이전</a></li>
        {% endif %}
      
        {% for i in pager.range %}    
        <li><a href="{% url 'notice:listPage' i %}">{{i}}</a></li>    
        {% endfor %}

        {% if pager.next %}
        <li><a href="{% url 'notice:listPage' pager.lastNum %}">다음</a></li>
        {% endif %}

    </ul>
    <a href="{% url 'notice:write' %}" class="btn btn-danger">Write</a>
</div>
{% endblock contents %}

notice/templates/notice/select.html
{% extends 'base.html' %}

{% block contents %}
<div class="container">
    <h2>{{board}}</h2>
    <table class="table table-striped">   
        <tr>
            <td>Num</td>
            <td>Title</td>
            <td>Writer</td>
            <td>Date</td>
            <td>Hit</td>
        </tr>
          
        <tr>
            <td>{{vo.num}}</td>
            <td>{{vo.title}}</td>
            <td>{{vo.writer}}</td>
            <td>{{vo.date}}</td>
            <td>{{vo.hit}}</td>
        </tr>
    </table>
    <div>
        <a href="{% url 'notice:update' vo.num %}" class="btn btn-primary">Update</a>
        <a href="{% url 'notice:delete' vo.num %}" class="btn btn-danger">Delete</a>
    </div>

</div>
{% endblock contents %}

notice/templates/notice/write.html
{% extends 'base.html' %}

{% block contents %}
<div class="container">
    <h1>{{board}}</h1>
    <form action="" method="post">
        {% csrf_token  %}
        <input type="hidden" id="num" name="num" value="{{vo.num}}">
        <div class="form-group">
          <label for="title">title</label>
          <input type="text" class="form-control" id="title" name="title" value="{{vo.title}}">
        </div>
        <div class="form-group">
          <label for="writer">writer</label>
          <input type="text" class="form-control" id="writer" name="writer" value="{{vo.writer}}">
        </div>
        <div class="form-group">
          <label for="contents">contents</label>
          <textarea cols="" rows="" class="form-control" id="contents" name="contents">{{vo.contents}}</textarea>
        </div>   
        <button type="submit" class="btn btn-default">Submit</button>
      </form>

</div>
{% endblock contents %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My title{% endblock title %}</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    {% block script1 %}
    {% endblock script1 %}
    {% block css %}
    {% endblock css %}
</head>
<body>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="#">WebSiteName</a>
          </div>
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Page 1 <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Page 1-1</a></li>
                <li><a href="#">Page 1-2</a></li>
                <li><a href="#">Page 1-3</a></li>
              </ul>
            </li>
            <li><a href="#">Page 2</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
            <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
          </ul>
        </div>
      </nav>
        
      {% block contents %}
      {% endblock contents %}

      {% block script2 %}
      {% endblock script2 %}

</body>
</html>